export { SpinupMail } from "@/client";
export type {
  CreateEmailAddressOptions,
  CreateEmailAddressInput,
  CreateEmailAddressRequest,
  CreateEmailAddressResponse,
  CreateIntegrationRequest,
  DeleteEmailAddressOptions,
  DeleteEmailAddressResponse,
  DeleteEmailOptions,
  DeleteEmailResponse,
  DeleteIntegrationResponse,
  DomainConfig,
  EmailTimestampFilter,
  EmailActivityResponse,
  EmailAddress,
  EmailAddressListResponse,
  EmailDetail,
  EmailListItem,
  EmailListResponse,
  EmailSummaryResponse,
  GetEmailActivityOptions,
  GetEmailAddressOptions,
  GetEmailAttachmentOptions,
  GetEmailOptions,
  GetEmailRawOptions,
  GetEmailSummaryOptions,
  InboxPollOptions,
  InboxPollResult,
  IntegrationOptions,
  ListEmailAddressesOptions,
  ListIntegrationDispatchesOptions,
  ListIntegrationDispatchesParams,
  ListIntegrationDispatchesResponse,
  ListIntegrationsResponse,
  ListEmailsOptions,
  ListRecentAddressActivityOptions,
  OrganizationIntegration,
  RecentAddressActivityResponse,
  ReplayIntegrationDispatchResponse,
  SpinupMailOptions,
  SpinupMailClient,
  SpinupMailDomainsApi,
  SpinupMailAddressesApi,
  SpinupMailEmailsApi,
  SpinupMailStatsApi,
  SpinupMailIntegrationsApi,
  SpinupMailInboxesApi,
  UpdateEmailAddressOptions,
  UpdateEmailAddressRequest,
  ValidateIntegrationConnectionRequest,
  ValidateIntegrationConnectionResponse,
  WaitForEmailOptions,
} from "@/client";
export {
  SpinupMailApiError,
  SpinupMailError,
  SpinupMailTimeoutError,
  SpinupMailValidationError,
} from "@/errors";
export { SpinupMailFile } from "@/file";
export {
  SpinupMailAgentClient,
  createAgentCredentialToken,
  generateAgentSecret,
} from "@/agent-client";
export { callAgentMcpTool, createAgentMcpTools } from "@/mcp";
export type {
  AgentCallInput,
  AgentIdempotentRequestOptions,
  AgentRequestOptions,
  CreateAgentClientOptions,
  EnrollAgentInput,
  EnrollAgentResult,
} from "@/agent-client";
