export { SpinupMail } from "@/client";
export type {
  CreateEmailAddressOptions,
  CreateEmailAddressInput,
  CreateEmailAddressRequest,
  CreateEmailAddressResponse,
  DeleteEmailAddressOptions,
  DeleteEmailAddressResponse,
  DeleteEmailOptions,
  DeleteEmailResponse,
  DomainConfig,
  EmailTimestampFilter,
  EmailActivityResponse,
  EmailAddress,
  EmailAddressListResponse,
  EmailDetail,
  EmailListItem,
  EmailListResponse,
  EmailSummaryResponse,
  GetEmailActivityOptions,
  GetEmailAddressOptions,
  GetEmailAttachmentOptions,
  GetEmailOptions,
  GetEmailRawOptions,
  GetEmailSummaryOptions,
  InboxPollOptions,
  InboxPollResult,
  ListEmailAddressesOptions,
  ListEmailsOptions,
  ListRecentAddressActivityOptions,
  RecentAddressActivityResponse,
  SpinupMailOptions,
  SpinupMailClient,
  SpinupMailDomainsApi,
  SpinupMailAddressesApi,
  SpinupMailEmailsApi,
  SpinupMailStatsApi,
  SpinupMailInboxesApi,
  UpdateEmailAddressOptions,
  UpdateEmailAddressRequest,
  WaitForEmailOptions,
} from "@/client";
export {
  SpinupMailApiError,
  SpinupMailError,
  SpinupMailTimeoutError,
  SpinupMailValidationError,
} from "@/errors";
export { SpinupMailFile } from "@/file";
