export const EMAIL_LIST_LIMIT_DEFAULT = 20;
export const EMAIL_LIST_LIMIT_MAX = 100;
export const EMAIL_MAX_BYTES_DEFAULT = 512 * 1024;
export const EMAIL_ATTACHMENT_MAX_BYTES_DEFAULT = 10 * 1024 * 1024;
export const EMAIL_ATTACHMENT_NAME_FALLBACK = "attachment";
export const EMAIL_BODY_MAX_BYTES_DEFAULT = 512 * 1024;
export const EMAIL_RAW_R2_CONTENT_TYPE = "message/rfc822";

export const AUTH_VERIFICATION_RESEND_COOLDOWN_SECONDS = 60;
export const AUTH_VERIFICATION_RESEND_IP_WINDOW_SECONDS = 5 * 60;
export const AUTH_VERIFICATION_RESEND_IP_MAX_ATTEMPTS = 5;
