import { z, type ZodType } from "zod";
import {
  agentApproveDraftRequestSchema,
  agentAttachmentPathSchema,
  agentCapabilitiesResponseSchema,
  agentCreateDraftRequestSchema,
  agentCreateEnrollmentRequestSchema,
  agentCreateInboxRequestSchema,
  agentCredentialListResponseSchema,
  agentDraftListQuerySchema,
  agentDraftListResponseSchema,
  agentDraftResponseSchema,
  agentEmptyRequestSchema,
  agentEnrollRequestSchema,
  agentEnrollResponseSchema,
  agentEnrollmentResponseSchema,
  agentEventListResponseSchema,
  agentFleetControlRequestSchema,
  agentFleetControlResponseSchema,
  agentIdPathSchema,
  agentIdempotencyKeySchema,
  agentInboxListResponseSchema,
  agentInboxResponseSchema,
  agentListMessagesQuerySchema,
  agentListQuerySchema,
  agentListThreadsQuerySchema,
  agentMessageListResponseSchema,
  agentMessageResponseSchema,
  agentOkResponseSchema,
  agentPrincipalListResponseSchema,
  agentProviderEventRequestSchema,
  agentProviderEventResponseSchema,
  agentSendingPolicyRequestSchema,
  agentSendingPolicyResponseSchema,
  agentSubmissionResponseSchema,
  agentSubmissionListResponseSchema,
  agentSubmitDraftRequestSchema,
  agentThreadListResponseSchema,
  agentThreadResponseSchema,
  agentUpdateDraftRequestSchema,
  agentUsageResponseSchema,
  type AgentCapability,
} from "./agent-resources";

export type AgentOperationAuth =
  | "public"
  | "enrollment-token"
  | "agent"
  | "human-or-agent"
  | "human-admin"
  | "human-admin-2fa"
  | "platform-operator"
  | "provider";

export type AgentOperationDefinition = {
  method: "GET" | "POST" | "PATCH" | "PUT" | "DELETE";
  path: string;
  auth: AgentOperationAuth;
  capability?: AgentCapability;
  idempotent: boolean;
  summary: string;
  description?: string;
  params?: ZodType;
  query?: ZodType;
  body?: ZodType;
  response?: ZodType;
  responseKind?: "json" | "text" | "binary" | "empty";
  successStatus: number;
  mcp: boolean;
};

const operation = <T extends AgentOperationDefinition>(definition: T) =>
  definition;

export const agentOperations = {
  getCapabilities: operation({
    method: "GET",
    path: "/api/v1/capabilities",
    auth: "human-or-agent",
    idempotent: false,
    summary: "Inspect the authenticated v1 actor and capabilities",
    response: agentCapabilitiesResponseSchema,
    successStatus: 200,
    mcp: true,
  }),
  createEnrollment: operation({
    method: "POST",
    path: "/api/v1/enrollments",
    auth: "human-admin-2fa",
    idempotent: true,
    summary: "Create a bounded one-time agent enrollment",
    body: agentCreateEnrollmentRequestSchema,
    response: agentEnrollmentResponseSchema,
    successStatus: 201,
    mcp: false,
  }),
  enrollAgent: operation({
    method: "POST",
    path: "/api/v1/agent/enroll",
    auth: "enrollment-token",
    idempotent: true,
    summary: "Exchange an enrollment for an agent credential",
    description:
      "The credential ID and secret are generated by the client. The service stores only the secret hash.",
    body: agentEnrollRequestSchema,
    response: agentEnrollResponseSchema,
    successStatus: 201,
    mcp: false,
  }),
  listAgents: operation({
    method: "GET",
    path: "/api/v1/agents",
    auth: "human-admin",
    idempotent: false,
    summary: "List agent principals",
    response: agentPrincipalListResponseSchema,
    successStatus: 200,
    mcp: false,
  }),
  revokeAgent: operation({
    method: "DELETE",
    path: "/api/v1/agents/{id}",
    auth: "human-admin",
    idempotent: false,
    summary: "Revoke an agent and its credentials",
    params: agentIdPathSchema,
    responseKind: "empty",
    successStatus: 204,
    mcp: false,
  }),
  listCredentials: operation({
    method: "GET",
    path: "/api/v1/credentials",
    auth: "human-admin",
    idempotent: false,
    summary: "List agent credentials without secrets",
    response: agentCredentialListResponseSchema,
    successStatus: 200,
    mcp: false,
  }),
  revokeCredential: operation({
    method: "DELETE",
    path: "/api/v1/credentials/{id}",
    auth: "human-admin",
    idempotent: false,
    summary: "Revoke an agent credential",
    params: agentIdPathSchema,
    responseKind: "empty",
    successStatus: 204,
    mcp: false,
  }),
  createInbox: operation({
    method: "POST",
    path: "/api/v1/inboxes",
    auth: "agent",
    capability: "inboxes:create",
    idempotent: true,
    summary: "Create a persistent granted inbox",
    body: agentCreateInboxRequestSchema,
    response: agentInboxResponseSchema,
    successStatus: 201,
    mcp: true,
  }),
  listInboxes: operation({
    method: "GET",
    path: "/api/v1/inboxes",
    auth: "human-or-agent",
    capability: "inboxes:read",
    idempotent: false,
    summary: "List accessible inboxes",
    query: agentListQuerySchema,
    response: agentInboxListResponseSchema,
    successStatus: 200,
    mcp: true,
  }),
  deleteInbox: operation({
    method: "DELETE",
    path: "/api/v1/inboxes/{id}",
    auth: "human-or-agent",
    capability: "inboxes:delete",
    idempotent: false,
    summary: "Delete and permanently tombstone an inbox address",
    params: agentIdPathSchema,
    responseKind: "empty",
    successStatus: 204,
    mcp: true,
  }),
  listMessages: operation({
    method: "GET",
    path: "/api/v1/messages",
    auth: "human-or-agent",
    capability: "messages:read",
    idempotent: false,
    summary: "Search messages in a granted inbox",
    query: agentListMessagesQuerySchema,
    response: agentMessageListResponseSchema,
    successStatus: 200,
    mcp: true,
  }),
  getMessage: operation({
    method: "GET",
    path: "/api/v1/messages/{id}",
    auth: "human-or-agent",
    capability: "messages:read",
    idempotent: false,
    summary: "Get one message from a granted inbox",
    params: agentIdPathSchema,
    response: agentMessageResponseSchema,
    successStatus: 200,
    mcp: true,
  }),
  getRawMessage: operation({
    method: "GET",
    path: "/api/v1/messages/{id}/raw",
    auth: "human-or-agent",
    capability: "messages:read",
    idempotent: false,
    summary: "Download the private raw MIME message",
    params: agentIdPathSchema,
    responseKind: "binary",
    successStatus: 200,
    mcp: false,
  }),
  getAttachment: operation({
    method: "GET",
    path: "/api/v1/messages/{id}/attachments/{attachmentId}",
    auth: "human-or-agent",
    capability: "messages:read",
    idempotent: false,
    summary: "Download a private message attachment",
    params: agentAttachmentPathSchema,
    responseKind: "binary",
    successStatus: 200,
    mcp: false,
  }),
  listThreads: operation({
    method: "GET",
    path: "/api/v1/threads",
    auth: "human-or-agent",
    capability: "messages:read",
    idempotent: false,
    summary: "List RFC-reference threads in a granted inbox",
    query: agentListThreadsQuerySchema,
    response: agentThreadListResponseSchema,
    successStatus: 200,
    mcp: true,
  }),
  getThread: operation({
    method: "GET",
    path: "/api/v1/threads/{id}",
    auth: "human-or-agent",
    capability: "messages:read",
    idempotent: false,
    summary: "Get a thread and its messages",
    params: agentIdPathSchema,
    response: agentThreadResponseSchema,
    successStatus: 200,
    mcp: true,
  }),
  pollEvents: operation({
    method: "GET",
    path: "/api/v1/events",
    auth: "human-or-agent",
    capability: "events:read",
    idempotent: false,
    summary: "Poll durable events with a stable cursor",
    query: agentListQuerySchema,
    response: agentEventListResponseSchema,
    successStatus: 200,
    mcp: true,
  }),
  createDraft: operation({
    method: "POST",
    path: "/api/v1/drafts",
    auth: "human-or-agent",
    capability: "drafts:write",
    idempotent: true,
    summary: "Create a versioned immutable-on-submit draft",
    body: agentCreateDraftRequestSchema,
    response: agentDraftResponseSchema,
    successStatus: 201,
    mcp: true,
  }),
  updateDraft: operation({
    method: "PATCH",
    path: "/api/v1/drafts/{id}",
    auth: "human-or-agent",
    capability: "drafts:write",
    idempotent: false,
    summary: "Compare-and-swap draft content",
    params: agentIdPathSchema,
    body: agentUpdateDraftRequestSchema,
    response: agentDraftResponseSchema,
    successStatus: 200,
    mcp: true,
  }),
  listDrafts: operation({
    method: "GET",
    path: "/api/v1/drafts",
    auth: "human-or-agent",
    capability: "drafts:write",
    idempotent: false,
    summary: "List drafts for a granted inbox",
    query: agentDraftListQuerySchema,
    response: agentDraftListResponseSchema,
    successStatus: 200,
    mcp: true,
  }),
  approveDraft: operation({
    method: "POST",
    path: "/api/v1/drafts/{id}/approve",
    auth: "human-admin",
    idempotent: true,
    summary: "Approve the exact canonical draft",
    params: agentIdPathSchema,
    body: agentApproveDraftRequestSchema,
    response: agentDraftResponseSchema,
    successStatus: 200,
    mcp: false,
  }),
  submitDraft: operation({
    method: "POST",
    path: "/api/v1/drafts/{id}/send",
    auth: "agent",
    capability: "messages:send",
    idempotent: true,
    summary: "Reserve quota and queue a policy-compliant draft once",
    params: agentIdPathSchema,
    body: agentSubmitDraftRequestSchema,
    response: agentSubmissionResponseSchema,
    successStatus: 202,
    mcp: true,
  }),
  listSubmissions: operation({
    method: "GET",
    path: "/api/v1/submissions",
    auth: "human-or-agent",
    capability: "messages:send",
    idempotent: false,
    summary: "List submission and recipient delivery outcomes",
    query: agentDraftListQuerySchema,
    response: agentSubmissionListResponseSchema,
    successStatus: 200,
    mcp: true,
  }),
  getSendingPolicy: operation({
    method: "GET",
    path: "/api/v1/sending-policy",
    auth: "human-admin",
    idempotent: false,
    summary: "Inspect sending gates and recipient rules",
    response: agentSendingPolicyResponseSchema,
    successStatus: 200,
    mcp: false,
  }),
  updateSendingPolicy: operation({
    method: "PUT",
    path: "/api/v1/sending-policy",
    auth: "human-admin",
    idempotent: false,
    summary: "Update sending and recipient allowlist policy",
    body: agentSendingPolicyRequestSchema,
    response: agentOkResponseSchema,
    successStatus: 200,
    mcp: false,
  }),
  getUsage: operation({
    method: "GET",
    path: "/api/v1/usage",
    auth: "human-admin",
    idempotent: false,
    summary: "Inspect pilot entitlement and recipient usage",
    response: agentUsageResponseSchema,
    successStatus: 200,
    mcp: false,
  }),
  recordProviderEvent: operation({
    method: "POST",
    path: "/api/v1/provider/events",
    auth: "provider",
    idempotent: false,
    summary: "Record a provider delivery event",
    body: agentProviderEventRequestSchema,
    response: agentProviderEventResponseSchema,
    successStatus: 202,
    mcp: false,
  }),
  getFleetControl: operation({
    method: "GET",
    path: "/api/v1/operator/fleet",
    auth: "platform-operator",
    idempotent: false,
    summary: "Inspect the platform-wide outbound kill switch",
    response: agentFleetControlResponseSchema,
    successStatus: 200,
    mcp: false,
  }),
  updateFleetControl: operation({
    method: "PUT",
    path: "/api/v1/operator/fleet",
    auth: "platform-operator",
    idempotent: false,
    summary: "Update the platform-wide outbound kill switch",
    body: agentFleetControlRequestSchema,
    response: agentFleetControlResponseSchema,
    successStatus: 200,
    mcp: false,
  }),
} as const;

export type AgentOperationName = keyof typeof agentOperations;

export const agentOperationInputSchema = (
  definition: AgentOperationDefinition
) =>
  z
    .object({
      params: definition.params ?? agentEmptyRequestSchema.optional(),
      query: definition.query ?? agentEmptyRequestSchema.optional(),
      body: definition.body ?? agentEmptyRequestSchema.optional(),
      idempotencyKey: definition.idempotent
        ? agentIdempotencyKeySchema
        : agentIdempotencyKeySchema.optional(),
    })
    .strict();

export const agentMcpOperationNames = (
  Object.entries(agentOperations) as Array<
    [AgentOperationName, AgentOperationDefinition]
  >
)
  .filter(([, definition]) => definition.mcp)
  .map(([name]) => name);
