declare global {
  interface CloudflareBindings {
    API_KEY_RATE_LIMIT_MAX?: string;
    API_KEY_RATE_LIMIT_WINDOW?: string;
    AUTH_CHANGE_EMAIL_RATE_LIMIT_MAX?: string;
    AUTH_CHANGE_EMAIL_RATE_LIMIT_WINDOW?: string;
    AUTH_ALLOWED_EMAIL_DOMAIN?: string;
    AUTH_RATE_LIMIT_MAX?: string;
    AUTH_RATE_LIMIT_WINDOW?: string;
    BETTER_AUTH_SECRET?: string;
    CORS_ORIGIN?: string;
    DASHBOARD_BASE_URL?: string;
    ENABLE_E2E_TEST_UTILS?: string;
    E2E_TEST_SECRET?: string;
    EMAIL_ATTACHMENTS_ENABLED?: string;
    EMAIL_ATTACHMENT_MAX_TOTAL_BYTES_PER_ORGANIZATION?: string;
    EMAIL_DOMAINS?: string;
    EMAIL_FORWARD_TO?: string;
    EMAIL_STORE_HEADERS_IN_DB?: string;
    EMAIL_STORE_RAW_IN_DB?: string;
    EMAIL_STORE_RAW_IN_R2?: string;
    FORCED_MAIL_PREFIX?: string;
    INTEGRATION_DISPATCH_QUEUE?: Queue<unknown>;
    INTEGRATION_QUEUE_BASE_DELAY_SECONDS?: string;
    INTEGRATION_QUEUE_JITTER_SECONDS?: string;
    INTEGRATION_QUEUE_MAX_DELAY_SECONDS?: string;
    INTEGRATION_QUEUE_RETRY_WINDOW_SECONDS?: string;
    INTEGRATION_SECRET_ENCRYPTION_KEY?: string;
    MAX_ADDRESSES_PER_ORGANIZATION?: string;
    MAX_RECEIVED_EMAILS_PER_ADDRESS?: string;
    MAX_RECEIVED_EMAILS_PER_ORGANIZATION?: string;
    RESEND_FROM_EMAIL?: string;
  }
}

export {};
