# For more details on how to configure Wrangler, refer to:
# https://developers.cloudflare.com/workers/wrangler/configuration/

name = "spinupmail"
main = "src/index.ts"
compatibility_date = "2025-03-01"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[placement]
mode = "smart"

[[d1_databases]]
binding = "SUM_DB"
database_name = "SUM_DB"
database_id = "a5ed1fb3-600a-45bb-991f-ad8be7170c49"
migrations_dir = "drizzle"

[[kv_namespaces]]
binding = "SUM_KV"
id = "442502dbafb4409999092c94e7784fad"

[[r2_buckets]]
bucket_name = "spinupmail-attachments"
binding = "R2_BUCKET"

[[send_email]]
name = "EMAIL"

[vars]
EMAIL_DOMAIN = "spinupmail.com"
EMAIL_DOMAINS = "spinupmail.com,spinuptest.com"
EMAIL_MAX_BYTES = "10485760"
EMAIL_BODY_MAX_BYTES = "524288"
EMAIL_ATTACHMENT_MAX_BYTES = "10485760"

# To protect the database id, kv id, we ignore this
# file when committing to the repo by running once:
# git update-index --assume-unchanged wrangler.toml
#
# Put back in git if you need to commit this file:
# git update-index --no-assume-unchanged wrangler.toml
